version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    environment:
    - DEBUG=True
    ports:
      - "8000:8000"
    depends_on:
      - nginx
  nginx:
    images: nginix:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etx/nginx/nginx.conf
    depends_on:
      - web
